config/routes.rb
Rails.application.routes.draw do



  get 'downgrade/new'

  get 'downgrade/create'

  devise_for :users, controllers: {registrations: "registrations"}
  
  get 'welcome/index'
  
  get 'welcome/about'
  
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create]
  
  resources :downgrade, only: [:new, :create]

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :wikis
  has_many :collaborators
  has_many :wiki_collaborations, through: :collaborators, source: :wiki
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  after_initialize {self.role ||= :standard}
  
  enum role: [:standard, :premium, :admin]
  
  def reset_to_public
    self.wikis.each {|wiki| puts wiki.make_public}
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators, source: :user
  
  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :user, presence: true
  
  after_initialize :initialize_privacy
  
  def make_public
    update_attributes(private: false)
  end
  
  private
  
  def initialize_privacy
    if self.private.nil?
      self.private = false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  
  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_url, alert: "You do not have access to do that"
  end
  
  private
      
    def authorize_index
        if current_user.try(:admin?)
            @wikis = Wiki.all
        elsif current_user.try(:premium?)
            @wikis = Wiki.where(private: false) | current_user.wiki_collaborations | current_user.wikis
        elsif current_user.try(:standard?)
            @wikis = Wiki.where(private: false) | current_user.wiki_collaborations
        else
            @wikis = Wiki.where(private: false)
        end
    end
    
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    
    # Creates a Stripe Customer object, for associating with the charge
    
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    
    charge = Stripe::Charge.create(
      customer: customer.id, # This is not user_id but rather the id generated for Stripe::Customer
      amount: 15_00,
      description: "Blocipedia Premium Membership - #{current_user.email}",
      currency: 'usd'
    )
    
    current_user.update_attributes(role: 'premium')
    
    flash[:notice] = "Thanks for your purchase of premium membership, #{current_user.email}. You can now create private wikis."
    
    redirect_to root_path
    
    rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "Blocipedia Premium Membership - #{current_user.email}",
      amount: 15_00
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
=begin  def update
      @wiki = Wiki.find(params[:wiki_id])
      authorize @wiki
      
      if @wiki.update(wiki_params)
          flash[:notice] = "Wiki was updated."
          redirect_to @wiki
      else
          flash[:alert] = "There was an error saving the wiki page. Please try again."
          render :edit
      end
  end
=end
  def create
    user = User.find_by_email(params[:collaborator][:user])
    @wiki = Wiki.find(params[:wiki_id])
    
    if @wiki.users.include?(user)
      flash[:alert] = "#{user.email} has already been added as a collaborator"
      redirect_to edit_wiki_path(@wiki)
    else
      if Collaborator.create(user_id: user.id, wiki_id: @wiki.id)
        flash[:notice] = "#{user.email} is now a collaborator"
      else
        flash[:alert] = "#{user.email} was not added as a collaborator"
      end
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def destroy
    user = User.find(params[:user_id])
    @wiki = Wiki.find(params[:wiki_id])
    collaborator = Collaborator.find_by(params[:user_id])
    
    if collaborator.destroy
      flash[:notice] = "#{collaborator.user.email} is no longer a collaborator"
    else
      flash[:alert] = "#{collaborator.user.email} has not been removed as a collaborator"
    end
    redirect_to edit_wiki_path(@wiki)
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def new
  end

  def create
    current_user.update_attributes(role: 'standard')
    current_user.reset_to_public
    
    flash[:notice] = "You have successfully downgraded your account."
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private
    
    def sign_up_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def account_update_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password) 
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  #  if user_signed_in?
  #    redirect_to wiki_pathll
  #  end
      
  end

  def about
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  after_action :verify_authorized, except: [:index, :show]
  
  def index
    authorize_index
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    @user_emails = User.where.not(id: current_user.id || @wiki.users.pluck(:id)).map(&:email)
    authorize @wiki
  end
  
  def create 
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash[:alert] = "Unable to save wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @user_emails = User.where.not(id: current_user.id || @wiki.users.pluck(:id)).map(&:email)
    authorize @wiki
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash[:alert] = "Unable to update wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
  
  private
  
  def set_wiki
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def markdown(text)
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
        return markdown.render(text).html_safe
    end
    
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<br />
<%= form_tag charges_path do %>
    <div class='col-md-10'>
        <h1>Upgrade to Premium</h1>
        <p>For a single payment of $15, you gain the ability on this account to create private wikis only accessible to you and a group of collaborators you'll have the ability to pick</p>
        <br />
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" 
        data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
    </div>
<% end %>
    

app/views/collaborators/_collaborator_form.html.erb
<% if current_user.admin? || current_user.premium? %>
    <div class='field'>
        <%= form_for [@wiki, Collaborator.new] do |c| %>
            <%= c.label :collaborators %><br />
            <%= c.select :user, options_for_select(@user_emails, :selected => params[:user], class: 'form-control') %><br /><br />
            <%= c.submit 'Add Collaborator', class: 'btn btn-primary' %>
        <% end %>
            
        <% if @wiki.users.any? %>
            <h3>Current Collaborators</h3>
            <% @wiki.users.each do |user| %>
                <b><p>
                    <%= user.email %> |<%= link_to "x", wiki_collaborator_path(user_id: user.id, wiki_id: @wiki.id), method: :delete %>|   
                </p></b>
            <% end %>
        <% end %>    
    </div>
<% else %>
    <h3>Current Collaborators</h3>
    <% @wiki.users.each do |user| %>
        <% if user.email == current_user.email %>
            <b><p>
                <%= current_user.email %> |<%= link_to "x", wiki_collaborator_path(user_id: user.id, wiki_id: @wiki.id), method: :delete %>|   
            </p></b>
        <% end %>
    <% end %>
<% end %>

app/views/downgrade/new.html.erb
<br />
<div class='col-md-10'>
    <h1>Downgrade Your Account</h1>
    <p>By clicking the button below, you agree to downgrade your account to standard status. With the standard status
    you will be unable to create private wikis and add collaborator to your wiki. All of your private wikis will be 
    be viewable to the public after downgrading as well. In order to obtain a premium membership
    on this account after downgrading, you will need to pay another $15 upgrade charge.</p>
    <br />
    <%= link_to "Downgrade", downgrade_create_path, class: 'btn btn-danger', 
    data: {confirm: 'Are you sure you want to downgrade your account from premium status to standard status?'} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubypedia</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class='container'>
      <ul class="nav nav-tabs pull-left">
        <li><%= link_to "Rubypedia", root_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <% if user_signed_in? %>
          <% if current_user.role == 'standard' %>
            <li><%= link_to 'Upgrade to Premium', new_charge_path %></li>
          <% elsif current_user.role == 'premium' %>
            <li><%= link_to 'Downgrade your account', new_downgrade_path %></li>
          <% end %>
        <% end %>
      </ul>
      <div class='nav nav-tabs pull-right'>
        <% if current_user %>
          <p>Welcome, <%= current_user.email %>. <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
        <% else %>
          <p>
            <%= link_to "Sign Up", new_user_registration_path %> or 
            <%= link_to "Sign In", new_user_session_path %>
          </p>
        <% end %>
      </div>
      
      <br />
      <br />
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class='alert alert-warning'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/welcome/about.html.erb
<h1>About Rubypedia</h1>
<p>Rubypedia is a wiki-esque web application built in Rails5 by Lucas Cuba. Here you can sign up for an account and create/edit general knowledge articles. In order to create private posts and add others to those private posts, users must upgrade to premium status.
This application uses several gems to provide these services, including pundit, devise, and stripe.</p>

app/views/welcome/index.html.erb
<br />
<div class='jumbotron'>
    <h1>Rubypedia</h1><hr />
    <h3>Welcome to the finest repository of publically editable knowledge in all the internet!</h3>
    <% unless current_user %>
        <p><%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary' %> or <%= link_to "Sign in", new_user_session_path, class: 'btn btn-primary' %> today!</p>
    <% end %>
</div>

app/views/wikis/edit.html.erb
<h1 class='text-center'>Edit Wiki</h1>
<br />

<div class='row'>
    <div class='col-md-12'>
        <%= form_for @wiki do |f| %>
            <div class="form-group">
                <%= f.label :title %><br />
                <%= f.text_field :title, class: 'form-control', autofocus: true %>
            </div>
            <div class="form-group">
                <%= f.label :body %><br />
                <%= f.text_area :body, rows: 20, class: 'form-control' %>
            </div>
            <% if current_user.admin? || current_user.premium? || @wiki.users.include?(current_user) %>
                <div class='form-check'>
                    <%= f.check_box :private, class: 'form-check-input' %>
                    <%= f.label :private, class: 'form-check-label' do %> 
                    Private Wiki
                    <% end %>
                </div>
            <% end %>
            <div class='form-group'>
                <%= f.submit "Update Wiki", class: 'btn btn-success' %>
            </div><br />
        <% end %>
        <%= render partial: 'collaborators/collaborator_form' %>
    </div>
</div>

app/views/wikis/index.html.erb
<h1 class='text-center'>Wikis</h1>
<br />
<table class='table table-hover text-center'>
    <thead>
        <th></th>
        <% if user_signed_in? %>
            <th></th>
            <th></th>
        <% end %>
    </thead>
    <tbody>
        <% @wikis.each do |wiki| %>
            <% if !wiki.private || wiki.user_id == current_user.id || current_user.admin? || wiki.users.include?(current_user) %>
                <tr class='text-center'>
                    <td>
                        <h4><%= link_to wiki.title, wiki %></h4>
                    </td>
                    <% if user_signed_in? %>
                        <td>
                            <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-primary' %>  
                        </td>
                        <td>
                            <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger', redirect_to: :index, data: { confirm: 'Are you sure you want to delete this wiki?' } %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>
<% if user_signed_in? %>
    <div class='text-center'>
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
<% end %>

app/views/wikis/new.html.erb
<h1 class='text-center'>Create New Wiki</h1>
<br />

<div class='row'>
    <div class='col-md-12'>
        <%= form_for @wiki do |f| %>
            <div class="form-group">
                <%= f.label :title %><br />
                <%= f.text_field :title, class: 'form-control', autofocus: true %>
            </div>
            <div class="form-group">
                <%= f.label :body %><br />
                <%= f.text_area :body, rows: 20, class: 'form-control' %>
            </div>
            <% if current_user.admin? || current_user.premium? || @wiki.users.include?(current_user) %>
                <div class='form-check'>
                    <%= f.check_box :private, class: 'form-check-input' %>
                    <%= f.label :private, class: 'form-check-label' do %> 
                    Private Wiki
                    <% end %>
                </div>
            <% end %>
            <div class='form-group'>
                <%= f.submit "Create Wiki", class: 'btn btn-success' %>
            </div><br />
        <% end %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1 class='text-center'>
    <%= @wiki.title %><br />
    <small>
        by <%= @wiki.user.email %>
    </small>
</h1>

<div class='row'>
    <div class='col-md-12'>
        <p class='text-center'><%= markdown(@wiki.body) %></p>
    </div>
</div>
<% if user_signed_in? %>
    <div class='text-center'>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', redirect_to: :index, data: { confirm: 'Are you sure you want to delete this wiki?' } %>
    </div>
<% end %>